name = "TestReg"
uuid = "f4feee08-f972-4f20-bf02-2b154da61742"
repo = "https://github.com/dustpancake/test-registry"
description = "Test Registry"

[packages]
52523ca6-5629-4d1c-9198-fa6f7fce26dd = { name = "HelloWorld", path = "H/HelloWorld" }
